spring.application.name=spring-boot-wheather-report
server.port=8081

#spring.security.user.name=admin
#spring.security.user.password=sat@134

#/weather?q=London,uk&APPID=64350f8f4891a1be1e5bf6605fe33123

